// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uabdwvtcxinsdggyjepm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhYmR3dnRjeGluc2RnZ3lqZXBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NTY4OTMsImV4cCI6MjA2NDUzMjg5M30.VnEGnSi8PBMXwqVxJyWBBQvbK_kzl5TQ-BMRWfXPWv8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);